// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Models;

namespace WebApplication.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20220120235708_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApplication.Data.EmployeeLocation", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("WebApplication.Data.EmployeePhoneNumber", b =>
                {
                    b.Property<int>("EmployeePhoneNumber_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeePhoneNumber_ID");

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("WebApplication.Data.EmployeeRole", b =>
                {
                    b.Property<int>("EmpRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpRoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("WebApplication.Data.Employees", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpRoleID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeLocationLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeePhoneNumber_ID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location_ID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleEmpRoleID")
                        .HasColumnType("int");

                    b.HasKey("empId");

                    b.HasIndex("EmployeeLocationLocationID");

                    b.HasIndex("EmployeePhoneNumber_ID");

                    b.HasIndex("RoleEmpRoleID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebApplication.Data.Employees", b =>
                {
                    b.HasOne("WebApplication.Data.EmployeeLocation", "EmployeeLocation")
                        .WithMany("Employee")
                        .HasForeignKey("EmployeeLocationLocationID");

                    b.HasOne("WebApplication.Data.EmployeePhoneNumber", "EmployeePhoneNumber")
                        .WithMany("Employee")
                        .HasForeignKey("EmployeePhoneNumber_ID");

                    b.HasOne("WebApplication.Data.EmployeeRole", "Role")
                        .WithMany("Employee")
                        .HasForeignKey("RoleEmpRoleID");

                    b.Navigation("EmployeeLocation");

                    b.Navigation("EmployeePhoneNumber");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApplication.Data.EmployeeLocation", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WebApplication.Data.EmployeePhoneNumber", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WebApplication.Data.EmployeeRole", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
